### ISSUE TITLE
Document Mask creation process

### ISSUE THREAD

**Issue by Germanunkol** [mapillary/OpenSfM#598] opened 2020-05-14 10:58 UTC
How to mask images was a bit difficult to figure out. It took me a while to find out that the mask needs an extra extension (.png). I think a description in the documentation would really help.

In the meantime, the process can be figured out by reading all the comments in the original pull request: https://github.com/mapillary/OpenSfM/pull/132

See also #551

**Comment by YanNoun** [comment] 2021-03-15 10:46
Closing as it is a duplicate of https://github.com/mapillary/OpenSfM/issues/551

**Closed by YanNoun** 2021-03-15 10:46 UTC
