### ISSUE TITLE
Ceres-solver "termination: failure" issue?

### ISSUE THREAD

**Issue by rttgnck** [mapillary/OpenSfM#206] opened 2017-08-08 15:31 UTC
Ok, so I have been able to generate plenty of work so far. The issue I am running into is this on every one of my iterations since I got up and running. Likely an issue with my dependency installation(s).

2017-08-08 14:58:08,198 DJI_0114.JPG resection inliers: 134 / 291
2017-08-08 14:58:08,200 Adding DJI_0114.JPG to the reconstruction
**2017-08-08 14:58:08,425 Ceres Solver Report: Iterations: -2, Initial cost: -1.000000e+00, Final cost: -1.000000e+00, Termination: FAILURE**
2017-08-08 14:58:08,446 Bundle setup/run/teardown 0.107916116714/0.107196092606/0.0211818218231
2017-08-08 14:58:08,449 Removed outliers: 95

Where ceres solver report comes up with a failure. I am not sure where this stems from or where to start to find why there is an issue. Something does not seem right, iterations -2, and -1 for costs. I am wondering if it has/had anything to do with my Eigen3 dependency. I could not get 3.2.92 installed so I edited the file that requests the specific installation to accept 3.2.9.

If any one can help that would be greatly appreciated. At this point I am not sure how much this actually effects my results. Or if it is merely just not computing that portion because of a missing environment path or something.

**Comment by deltameter** [comment] 2017-09-14 04:55
did you get this solved?

**Comment by paulinus** [comment] 2017-09-21 10:04
This should not happen. @rttgnck could you provide a small set of images where you observe that? thanks!

**Comment by deltameter** [comment] 2017-09-30 00:50
This fails for me just on the provided Berlin dataset.

**Comment by deltameter** [comment] 2017-09-30 00:51
Even with my own images, it fails, but the pose reconstruction looks fairly decent.

**Comment by mjevanmarle** [comment] 2017-11-20 13:59
Did you solve this problem? I get the same error. Thanks!

**Comment by paulinus** [comment] 2017-11-21 16:27
@mjevanmarle is this happening to you on the Berlin dataset also?  I cannot reproduce it so maybe you could help to find out the problem. Can you send the versions of Ceres and Eigen that you have installed and which OS?

**Comment by YanNoun** [comment] 2021-03-15 09:02
No answer for a while, closing.

**Closed by YanNoun** 2021-03-15 09:02 UTC
