### ISSUE TITLE
render image given the camera position

### ISSUE THREAD

**Issue by Dhiraj100892** [mapillary/OpenSfM#561] opened 2020-03-12 20:28 UTC
Hi 
After running the reconstruction using OpenSfm, is it possible to render how the image will look given the camera location using python? 

I am not planning to provide random camera location, they will be very close to one of the predicted camera locations

In the opensfm viewer (browser one) I am able to navigate in the scene by clicking the buttons and it renders the corresponding RGB image but I am not able to figure out how to do it in python

**Comment by paulinus** [comment] 2020-03-30 20:50
If you can use opengl, you can reproduce what is done in the web viewer. That basically is:
- Create a 3D mesh object (read from reconstruction.meshed.json)
- Use GLSL shaders to paint it by projecting 3D points to the image
- Move the opengl camera arbitrarily 

If you want to do it without opengl, it will get harder because you will need to build some kind of 3D renderer, or at least a triangle rasterer.

**Comment by YanNoun** [comment] 2021-03-15 10:25
No answer in a while, closing.

**Closed by YanNoun** 2021-03-15 10:25 UTC
