### ISSUE TITLE
Image masks

### ISSUE THREAD

**Issue by jer5** [mapillary/OpenSfM#118] opened 2016-12-08 17:12 UTC
In some circumstances it would be useful to have certain parts of each image ignored (for example if some parts of the image are known to contain moving objects which would confuse the reconstruction process). Therefore it would be useful to have the option to supply a binary pixel mask with each image to indicate which parts of the image should be ignored.

The simplest way to supply the pixel mask is probably to have another mask image along side each real image. Alternatively an alpha channel on a single image could be abused to pass the information.

Using a specific colour in the image to indicate the masked area (e.g. setting all areas to be ignored to black) would be less useful as this would lose the image of the moving objects in the original image.

Another use case for this mask capability is where camera lens correction has been applied to the images, resulting in images that have a region around their edges where only some of the pixels contain valid data from the raw image.

**Comment by paulinus** [comment] 2016-12-16 14:31
That would be a nice feature to add @jer5.  The simplest way to do that would be to remove any feature outside the masks right after feature detection.

We have a very basic mask concept in place, which is a list of rectangles to ignore on every image. The use case for that is to remove static watermarks.

A binary bitmap per image would be better.

The code to modify is around https://github.com/mapillary/OpenSfM/blob/f80abbcb09a0ec6b016b967f291aa09f6567c39f/opensfm/features.py#L71-L86

Do you want to try implementing it?

**Comment by StrausMG** [comment] 2019-04-11 10:23
Could you clarify why the issue is not closed if #132 is merged?

**Closed** 2019-08-22 16:49 UTC
