### ISSUE TITLE
I want to solve problem ImportError: dlopen(/Users/evan/OpenSfM-0.1.0/opensfm/csfm.so, 2): Symbol not found: _PyUnicode_AsUTF8String

### ISSUE THREAD

**Issue by ghost** [mapillary/OpenSfM#504] opened 2019-12-05 08:21 UTC
now i installed opensfm-0.1.0
when i running bin/opensfm_run_all data/berlin

evan@evanui-MacBookPro OpenSfM-0.1.0 % bin/opensfm_run_all data/lund
Traceback (most recent call last):
  File "/Users/evan/OpenSfM-0.1.0/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/Users/evan/OpenSfM-0.1.0/opensfm/commands/__init__.py", line 2, in <module>
    import extract_metadata
  File "/Users/evan/OpenSfM-0.1.0/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/Users/evan/OpenSfM-0.1.0/opensfm/dataset.py", line 12, in <module>
    from opensfm import io
  File "/Users/evan/OpenSfM-0.1.0/opensfm/io.py", line 10, in <module>
    from opensfm import features
  File "/Users/evan/OpenSfM-0.1.0/opensfm/features.py", line 7, in <module>
    import csfm
ImportError: dlopen(/Users/evan/OpenSfM-0.1.0/opensfm/csfm.so, 2): Symbol not found: _PyUnicode_AsUTF8String
  Referenced from: /usr/local/opt/boost-python3/lib/libboost_python37.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python3/lib/libboost_python37.dylib

i don't know how to solve it

**Comment by paulinus** [comment] 2019-12-11 21:15
I'm not sure what the problem is from the logs but here are some ideas. Are you using opensfm version 0.1.0? if so I recommend you using either the current master branch or latest release 0.3.0.
Version 0.1.0 is old, did not support python 3 and had problems with recent versions of boost (which is why we switched to pybind)

**Comment by YanNoun** [comment] 2021-03-15 10:10
No answer in a while, closing.

**Closed by YanNoun** 2021-03-15 10:10 UTC
Labels: installation
